#!/bin/bash
sudo apt-get update
sudo apt-get install samba -y
sudo mkdir /srv/kozos
sudo chmod 777 /srv/kozos
sudo mkdir /srv/readonly
sudo chmod 755 /srv/readonly
sudo service smbd restart
sudo service smbd status

